version: "3.9"

#===============================FRONTEND_CONTAINER
services:
  frontend:
    container_name: front
    build:
      context: front/
      dockerfile: Dockerfile
    volumes:
      - frontend:/app
    ports:
      - 3000:3000
    env_file: .env
    networks:
      - game_network
  #==============================BACKEND_CONTAINER
  backend:
    container_name: back
    build:
      context: back/
      dockerfile: Dockerfile
    volumes:
      - backend:/src
    ports:
      - 5000:5000
    env_file: .env
    networks:
      - game_network
  #==============================POSTGRESQL
  postgredb:
    image: postgres:latest
    container_name: postgredb
    volumes:
      - postgredb:/var/lib/postgresql/data
    networks:
      - game_network
    env_file: .env
  #==============================VOLUMES
volumes:
  frontend:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${PWD}/front/app"
  backend:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${PWD}/back/src"
  postgredb:
#==============================NETWORK
networks:
  game_network:
    driver: bridge
